const API_BASE = ["localhost", "127.0.0.1"].includes(location.hostname) ? "http://localhost:8000" : "https://api-dining.agmentic.com";
const ACCESS_API = ["localhost", "127.0.0.1"].includes(location.hostname) ? "https://agmentic-homepage-leads.em-ameri94.workers.dev/api/showcase-access" : "/api/showcase-access";
const ACCESS_STORAGE_KEY = "agmentic_showcase_access_v1";
const state = { token:null, menu:null, quota:{remaining_questions:2,remaining_handshakes:2,location_available:true}, signals:new Map([["Menu","loaded"]]), busy:false };
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const modal=$("#toolModal"), modalBody=$("#modalBody"), conversation=$("#conversation");

let accessChallenge = null;
let accessEmail = "";
let resendTimer = null;
function setAccessStatus(message,isError=false){const status=$("#accessStatus");status.textContent=message;status.classList.toggle("error",isError)}
function setAccessBusy(form,busy){form.querySelectorAll("input,button[type=submit]").forEach(el=>el.disabled=busy)}
function unlockShowcase(){document.body.classList.add("access-granted");$("#accessGate").hidden=true}
async function accessRequest(path,body,token){const response=await fetch(`${ACCESS_API}/${path}`,{method:"POST",headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify(body||{})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||"We couldn't complete that request.");return data}
function beginResendCountdown(){clearInterval(resendTimer);let remaining=60;const button=$("#resendCode");button.disabled=true;button.textContent=`Resend in ${remaining}s`;resendTimer=setInterval(()=>{remaining-=1;if(remaining<=0){clearInterval(resendTimer);button.disabled=false;button.textContent="Send a new code"}else button.textContent=`Resend in ${remaining}s`},1000)}
async function sendAccessCode(email,website=""){const form=$("#emailAccessForm");setAccessBusy(form,true);setAccessStatus("Sending your secure code…");try{const data=await accessRequest("request-code",{email,website});accessChallenge=data.challenge_id;accessEmail=email.trim().toLowerCase();$("#codeEmail").textContent=accessEmail;form.hidden=true;$("#codeAccessForm").hidden=false;$("#accessCode").focus();setAccessStatus("Check your inbox. The code expires in 10 minutes.");beginResendCountdown()}catch(error){setAccessStatus(error.message,true)}finally{setAccessBusy(form,false)}}
async function restoreAccess(){const token=localStorage.getItem(ACCESS_STORAGE_KEY);if(!token)return;try{await accessRequest("status",{},token);unlockShowcase()}catch{localStorage.removeItem(ACCESS_STORAGE_KEY)}}

async function api(path,body){const response=await fetch(`${API_BASE}${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body||{})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.detail||"The demo service could not complete that action.");return data}
function toast(message){const el=$("#toast");el.textContent=message;el.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.hidden=true,3200)}
function updateQuota(quota){if(!quota)return;state.quota=quota;$("#questionQuota").textContent=quota.remaining_questions;$("#handshakeQuota").textContent=quota.remaining_handshakes;$("#chatLimitNote").textContent=quota.remaining_questions?`${quota.remaining_questions} live AI question${quota.remaining_questions===1?"":"s"} available.`:"Questions complete. You can still connect the agents.";$("#chatInput").disabled=!quota.remaining_questions;$("#sendButton").disabled=!quota.remaining_questions;$("#connectAgents").disabled=!quota.remaining_handshakes;$("#locationToolState").textContent=quota.location_available?"1 use":"Used"}
async function startSession(){if(state.token)return;const button=$("[data-start]");button.disabled=true;button.textContent="Starting secure session…";try{const data=await api("/demo/session",{});state.token=data.token;state.menu=structuredClone(data.menu);updateQuota(data.quota);button.textContent="Session ready ✓";$("#sandbox").scrollIntoView({behavior:"smooth"})}catch(error){button.disabled=false;button.textContent="Try again";toast(error.message)}}
function selectedValues(kind){return $$(`[data-choice="${kind}"] button.selected`).map(button=>button.textContent.trim())}
function config(){return{token:state.token,party_size:Number($("#partySize").value),budget_per_person:Number($("#budget").value),likes:selectedValues("likes"),dislikes:selectedValues("dislikes"),occasion:$("#occasion").value,menu:state.menu}}
async function syncConfig(){if(!state.token)await startSession();const data=await api("/demo/configure",config());updateQuota(data.quota)}
function appendMessage(role,text,loading=false){const article=document.createElement("article");article.className=`message ${role}-message${loading?" loading":""}`;article.innerHTML=`<span>${role==="agent"?"A":"Y"}</span><p></p>`;article.querySelector("p").textContent=text;conversation.append(article);conversation.scrollTop=conversation.scrollHeight;return article}
async function askAgent(text){if(state.busy||!text.trim()||!state.quota.remaining_questions)return;state.busy=true;appendMessage("user",text.trim());const loading=appendMessage("agent","Thinking from the current menu…",true);try{await syncConfig();const data=await api("/demo/chat",{token:state.token,message:text.trim()});loading.remove();appendMessage("agent",data.response);updateQuota(data.quota)}catch(error){loading.remove();appendMessage("agent",error.message);toast(error.message)}finally{state.busy=false}}

function openModal(kicker,title,html){$("#modalKicker").textContent=kicker;$("#modalTitle").textContent=title;modalBody.innerHTML=html;modal.hidden=false;document.body.style.overflow="hidden";$("#closeModal").focus()}
function closeModal(){modal.hidden=true;document.body.style.overflow=""}
function renderSignals(){$("#activeSignals").innerHTML=[...state.signals].map(([name,value])=>`<span>${escapeHtml(name)} · ${escapeHtml(value)}</span>`).join("")}

function showLimits(){openModal("SIMPLE BY DESIGN","A short, limited experience",`<div class="limit-list"><div><b>${state.quota.remaining_questions}</b> live AI questions</div><div><b>${state.quota.remaining_handshakes}</b> agent connections</div><div><b>${state.quota.location_available?1:0}</b> nearby lookup</div><div>Preset menu · no real booking or payment</div><div>Calendar, weather and voice call are clearly simulated</div></div>`)}
function showMenu(){const rows=state.menu.items.slice(0,5).map((item,index)=>`<label class="menu-row"><span><strong>${escapeHtml(item.name)}</strong><small>${escapeHtml(item.section)} · ${escapeHtml(item.description)}</small></span><input data-price="${index}" type="number" min="4" max="60" step="1" value="${price(item.price)}" aria-label="Price for ${escapeHtml(item.name)}"></label>`).join("");openModal("PRESET MENU · 5 ITEMS","A small menu to experiment with",`<div class="menu-editor">${rows}</div><div class="modal-actions"><button id="saveMenu" type="button">Save prices</button></div>`);$("#saveMenu").onclick=()=>{$$("[data-price]",modalBody).forEach(input=>state.menu.items[Number(input.dataset.price)].price=`€${Math.max(4,Math.min(60,Number(input.value)||4))}`);state.signals.set("Menu","prices edited");renderSignals();closeModal();toast("Prices saved. The next answer and negotiation will use them.")}}
function showCalendar(){openModal("SIMULATED CONNECTOR","Calendar signal",`<div class="limit-list"><div><strong>Client dinner with Acme</strong><br>Tonight · 19:00 · 4 attendees · Berlin Mitte</div><div>This is a demo calendar event. Confirming it adds business dinner context to the agent.</div></div><div class="modal-actions"><button id="useCalendar">Use this signal</button></div>`);$("#useCalendar").onclick=()=>{$("#occasion").value="Business dinner";$("#partySize").value=4;state.signals.set("Calendar","client dinner");renderSignals();closeModal();appendMessage("agent","I noticed a client dinner tonight. I’ll prioritize a business-appropriate choice.")}}
function showWeather(){openModal("SIMULATED CONNECTOR","Weather signal",`<div class="limit-list"><div><strong>Light rain around 19:00</strong><br>14°C · 80% chance of rain</div><div>The agent can turn this into an indoor-seating preference without sharing the full forecast.</div></div><div class="modal-actions"><button id="useWeather">Prefer indoor seating</button></div>`);$("#useWeather").onclick=()=>{state.signals.set("Weather","indoor preferred");renderSignals();closeModal();appendMessage("agent","Rain is likely, so I’ll keep indoor seating in the brief.")}}
let ringTimer=null,callTimer=null,callSeconds=0,audioContext=null;
function ringOnce(){try{audioContext=audioContext||new(window.AudioContext||window.webkitAudioContext)();const now=audioContext.currentTime;[0,.22].forEach(offset=>{const oscillator=audioContext.createOscillator(),gain=audioContext.createGain();oscillator.frequency.value=440;gain.gain.setValueAtTime(.0001,now+offset);gain.gain.exponentialRampToValueAtTime(.08,now+offset+.02);gain.gain.exponentialRampToValueAtTime(.0001,now+offset+.16);oscillator.connect(gain).connect(audioContext.destination);oscillator.start(now+offset);oscillator.stop(now+offset+.18)})}catch{}}
function startRinging(){ringOnce();ringTimer=setInterval(ringOnce,1600)}
function stopRinging(){clearInterval(ringTimer);ringTimer=null}
function speakAgent(text){if(!("speechSynthesis" in window))return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.rate=.92;utterance.pitch=1;window.speechSynthesis.speak(utterance)}
function showCall(){const screen=$("#callScreen");screen.hidden=false;document.body.style.overflow="hidden";screen.querySelector(".call-phone").classList.remove("connected");$("#callStatus").textContent="Incoming call…";$("#callTimer").hidden=true;$("#callTranscript").hidden=true;$("#callPriorities").hidden=true;$("#answerCall").hidden=false;$("#declineCall").hidden=false;$("#endCall").hidden=true;startRinging();$("#answerCall").focus()}
function answerCall(){stopRinging();$("#callScreen .call-phone").classList.add("connected");$("#callStatus").textContent="Connected";$("#callTimer").hidden=false;$("#callTranscript").hidden=false;$("#callPriorities").hidden=false;$("#answerCall").hidden=true;$("#declineCall").hidden=true;$("#endCall").hidden=false;callSeconds=0;$("#callTimer").textContent="00:00";clearInterval(callTimer);callTimer=setInterval(()=>{callSeconds+=1;$("#callTimer").textContent=`00:${String(callSeconds).padStart(2,"0")}`},1000);speakAgent("Hi, I’m your Fine Dining Agent. Before I negotiate, what should I prioritize? A quiet table, or the best price?")}
function endCall(message="Call ended"){stopRinging();clearInterval(callTimer);if("speechSynthesis" in window)window.speechSynthesis.cancel();$("#callScreen").hidden=true;document.body.style.overflow="";toast(message)}
function chooseCallPriority(priority){if(priority==="quiet"){state.signals.set("Call","quiet table");$("#occasion").value="Business dinner";speakAgent("Understood. I’ll prioritize a quiet table.");appendMessage("agent","Call noted: I’ll prioritize a quiet table.")}else{$("#budget").value="24";state.signals.set("Call","best price");speakAgent("Understood. I’ll prioritize the best price under twenty four euros.");appendMessage("agent","Call noted: I’ll prioritize the best value under €24.")}renderSignals();setTimeout(()=>endCall("Priority saved from the call."),1500)}
async function useLocation(){if(!state.quota.location_available){toast("The one live location lookup has already been used.");return}if(!navigator.geolocation){toast("Location is not supported in this browser.");return}openModal("LIVE CONNECTOR","Finding restaurants nearby",`<div class="limit-list"><div>Waiting for browser location permission…</div><div>Your coordinates are used for this lookup and are not included in the retailer handshake.</div></div>`);navigator.geolocation.getCurrentPosition(async position=>{try{if(!state.token)await startSession();const data=await api("/demo/location",{token:state.token,latitude:position.coords.latitude,longitude:position.coords.longitude,accuracy:position.coords.accuracy});updateQuota(data.quota);const restaurants=data.restaurants||[];modalBody.innerHTML=restaurants.length?`<div class="restaurant-list">${restaurants.map((restaurant,index)=>`<article class="restaurant-item"><div><strong>${escapeHtml(restaurant.name||"Nearby restaurant")}</strong><span>${escapeHtml(restaurant.address||restaurant.cuisine||"")} · ${Math.round(restaurant.distance_m||0)}m</span></div><button data-restaurant="${index}">Use context</button></article>`).join("")}</div>`:`<div class="limit-list"><div>No restaurant results were available for this location. The preset restaurant remains active.</div></div>`;$$('[data-restaurant]',modalBody).forEach(button=>button.onclick=()=>{const item=restaurants[Number(button.dataset.restaurant)];state.signals.set("Location",item.name||"nearby restaurant");renderSignals();closeModal();appendMessage("agent",`I found ${item.name}. For this limited demo I’ll keep Maison Lumière’s preset menu, but use the nearby-location context.`)})}catch(error){modalBody.innerHTML=`<div class="limit-list"><div>${escapeHtml(error.message)}</div></div>`}},error=>{modalBody.innerHTML=`<div class="limit-list"><div>Location was not shared: ${escapeHtml(error.message)}</div></div>`},{enableHighAccuracy:false,timeout:12000,maximumAge:60000})}

async function runHandshake(){if(state.busy||!state.quota.remaining_handshakes)return;state.busy=true;const button=$("#connectAgents");button.disabled=true;button.textContent="Connecting…";try{await syncConfig();const data=await api("/demo/handshake",{token:state.token});updateQuota(data.quota);$("#handshakeEmpty").hidden=true;$("#eventStream").innerHTML="";$("#offerCard").hidden=true;const events=data.events.length<=3?data.events:[data.events[0],data.events[Math.floor(data.events.length/2)],data.events[data.events.length-1]];for(const event of events){const item=document.createElement("li");item.innerHTML=`<small>${escapeHtml(event.speaker)} · ${escapeHtml(event.action)}</small><strong>${escapeHtml(event.message)}</strong>`;$("#eventStream").append(item);await wait(430)}const offer=data.offer;$("#offerTitle").textContent=offer.item.name;$("#offerDetails").textContent=`${offer.item.description} · ${offer.party_size} guests · ${offer.promotion}`;$("#listPrice").textContent=`€${offer.list_price.toFixed(2)}`;$("#offerPrice").textContent=`€${offer.offer_price.toFixed(2)}`;$("#budgetCheck").textContent=`Within €${offer.budget_per_person.toFixed(2)} budget`;$("#offerCard").hidden=false;$("#offerCard").focus()}catch(error){toast(error.message)}finally{state.busy=false;button.textContent="Connect agents →";button.disabled=!state.quota.remaining_handshakes}}
function price(value){const match=String(value).match(/[\d,.]+/);return match?Number(match[0].replace(",",".")):0}function wait(ms){return new Promise(resolve=>setTimeout(resolve,ms))}function escapeHtml(value){return String(value??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}

const toolActions={menu:showMenu,location:useLocation,calendar:showCalendar,weather:showWeather,call:showCall};
let guidedTool=null;
function closeGuide(){$("#guidePopover").hidden=true;guidedTool=null}
function openGuide(button){guidedTool=button.dataset.tool;$("#guideTitle").textContent=button.dataset.guideTitle;$("#guideCopy").textContent=button.dataset.guideCopy;const popover=$("#guidePopover"),rect=button.getBoundingClientRect();popover.hidden=false;const width=Math.min(285,window.innerWidth-28);popover.style.left=`${Math.min(window.innerWidth-width-14,Math.max(14,rect.left+rect.width/2-width/2))}px`;popover.style.top=`${Math.min(window.innerHeight-230,rect.bottom+10)}px`;$("#guideAction").focus()}
async function runGuidedTool(){const action=toolActions[guidedTool];closeGuide();if(!state.token)await startSession();if(!state.token)return;action?.()}

$("[data-start]").addEventListener("click",startSession);$("#showLimits").addEventListener("click",showLimits);$("#closeModal").addEventListener("click",closeModal);modal.addEventListener("click",event=>{if(event.target===modal)closeModal()});document.addEventListener("keydown",event=>{if(event.key!=="Escape")return;if(!$("#callScreen").hidden)endCall();else if(!modal.hidden)closeModal();else closeGuide()});
$$('[data-tool]').forEach(button=>button.addEventListener("click",()=>openGuide(button)));$("#closeGuide").addEventListener("click",closeGuide);$("#guideAction").addEventListener("click",runGuidedTool);document.addEventListener("click",event=>{if(!$("#guidePopover").hidden&&!event.target.closest("#guidePopover")&&!event.target.closest("[data-tool]"))closeGuide()});
$$('[data-choice="likes"] button').forEach(button=>button.addEventListener("click",()=>{$$('[data-choice="likes"] button').forEach(item=>item.classList.toggle("selected",item===button))}));$$('.suggested-questions button').forEach(button=>button.addEventListener("click",()=>askAgent(button.textContent)));$("#chatForm").addEventListener("submit",event=>{event.preventDefault();const input=$("#chatInput");const text=input.value;input.value="";askAgent(text)});$("#connectAgents").addEventListener("click",runHandshake);$("#restartDemo").addEventListener("click",()=>location.reload());
$("#answerCall").addEventListener("click",answerCall);$("#declineCall").addEventListener("click",()=>endCall("Call declined."));$("#endCall").addEventListener("click",()=>endCall());$$('[data-call-priority]').forEach(button=>button.addEventListener("click",()=>chooseCallPriority(button.dataset.callPriority)));renderSignals();
$("#emailAccessForm").addEventListener("submit",event=>{event.preventDefault();const form=new FormData(event.currentTarget);sendAccessCode(String(form.get("email")||""),String(form.get("website")||""))});
$("#codeAccessForm").addEventListener("submit",async event=>{event.preventDefault();const form=event.currentTarget;setAccessBusy(form,true);setAccessStatus("Verifying your code…");try{const data=await accessRequest("verify-code",{email:accessEmail,code:$("#accessCode").value.trim(),challenge_id:accessChallenge});localStorage.setItem(ACCESS_STORAGE_KEY,data.access_token);setAccessStatus("Access verified. Opening the showcase…");setTimeout(unlockShowcase,350)}catch(error){setAccessStatus(error.message,true);$("#accessCode").select()}finally{setAccessBusy(form,false)}});
$("#changeEmail").addEventListener("click",()=>{$("#codeAccessForm").hidden=true;$("#emailAccessForm").hidden=false;setAccessStatus("");$("#accessEmail").focus()});
$("#resendCode").addEventListener("click",()=>sendAccessCode(accessEmail));
restoreAccess();
