const API_BASE = ["localhost", "127.0.0.1"].includes(location.hostname) ? "http://localhost:8000" : "https://api-dining.agmentic.com";
const state = { token:null, menu:null, quota:{remaining_questions:2,remaining_handshakes:2,location_available:true}, signals:new Map([["Menu","loaded"]]), busy:false };
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const modal=$("#toolModal"), modalBody=$("#modalBody"), conversation=$("#conversation");

async function api(path,body){const response=await fetch(`${API_BASE}${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body||{})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.detail||"The demo service could not complete that action.");return data}
function toast(message){const el=$("#toast");el.textContent=message;el.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.hidden=true,3200)}
function updateQuota(quota){if(!quota)return;state.quota=quota;$("#questionQuota").textContent=quota.remaining_questions;$("#handshakeQuota").textContent=quota.remaining_handshakes;$("#chatLimitNote").textContent=quota.remaining_questions?`You can ask ${quota.remaining_questions} more LLM-powered question${quota.remaining_questions===1?"":"s"}.`:"Your two LLM questions are complete. You can still edit intent and run the handshake.";$("#chatInput").disabled=!quota.remaining_questions;$("#sendButton").disabled=!quota.remaining_questions;$("#connectAgents").disabled=!quota.remaining_handshakes;$("#locationToolState").textContent=quota.location_available?"Live":"Used"}
async function startSession(){if(state.token)return;const button=$("[data-start]");button.disabled=true;button.textContent="Starting secure session…";try{const data=await api("/demo/session",{});state.token=data.token;state.menu=structuredClone(data.menu);updateQuota(data.quota);button.textContent="Session ready ✓";$("#sandbox").scrollIntoView({behavior:"smooth"})}catch(error){button.disabled=false;button.textContent="Try again";toast(error.message)}}
function selectedValues(kind){return $$(`[data-choice="${kind}"] button.selected`).map(button=>button.textContent.trim())}
function config(){return{token:state.token,party_size:Number($("#partySize").value),budget_per_person:Number($("#budget").value),likes:selectedValues("likes"),dislikes:selectedValues("dislikes"),occasion:$("#occasion").value,menu:state.menu}}
async function syncConfig(){if(!state.token)await startSession();const data=await api("/demo/configure",config());updateQuota(data.quota)}
function appendMessage(role,text,loading=false){const article=document.createElement("article");article.className=`message ${role}-message${loading?" loading":""}`;article.innerHTML=`<span>${role==="agent"?"A":"Y"}</span><p></p>`;article.querySelector("p").textContent=text;conversation.append(article);conversation.scrollTop=conversation.scrollHeight;return article}
async function askAgent(text){if(state.busy||!text.trim()||!state.quota.remaining_questions)return;state.busy=true;appendMessage("user",text.trim());const loading=appendMessage("agent","Thinking from the current menu…",true);try{await syncConfig();const data=await api("/demo/chat",{token:state.token,message:text.trim()});loading.remove();appendMessage("agent",data.response);updateQuota(data.quota)}catch(error){loading.remove();appendMessage("agent",error.message);toast(error.message)}finally{state.busy=false}}

function openModal(kicker,title,html){$("#modalKicker").textContent=kicker;$("#modalTitle").textContent=title;modalBody.innerHTML=html;modal.hidden=false;document.body.style.overflow="hidden";$("#closeModal").focus()}
function closeModal(){modal.hidden=true;document.body.style.overflow=""}
function renderSignals(){$("#activeSignals").innerHTML=[...state.signals].map(([name,value])=>`<span>${escapeHtml(name)} · ${escapeHtml(value)}</span>`).join("")}

function showLimits(){openModal("YOUR SHOWCASE SESSION","Real capability, deliberate limits",`<div class="limit-list"><div><b>${state.quota.remaining_questions}</b> LLM questions remaining</div><div><b>${state.quota.remaining_handshakes}</b> agent handshakes remaining</div><div><b>${state.quota.location_available?1:0}</b> live location lookup remaining</div><div>Preset menu only · prices editable between €4 and €60</div><div>Calendar, weather, call and reservation are simulations</div></div>`)}
function showMenu(){const rows=state.menu.items.map((item,index)=>`<label class="menu-row"><span><strong>${escapeHtml(item.name)}</strong><small>${escapeHtml(item.section)} · ${escapeHtml(item.description)}</small></span><input data-price="${index}" type="number" min="4" max="60" step="1" value="${price(item.price)}" aria-label="Price for ${escapeHtml(item.name)}"></label>`).join("");openModal("PRESET MENU · EDITABLE PRICES","Maison Lumière menu",`<div class="menu-editor">${rows}</div><div class="modal-actions"><button id="saveMenu" type="button">Save menu prices</button></div>`);$("#saveMenu").onclick=()=>{$$("[data-price]",modalBody).forEach(input=>state.menu.items[Number(input.dataset.price)].price=`€${Math.max(4,Math.min(60,Number(input.value)||4))}`);state.signals.set("Menu","prices edited");renderSignals();closeModal();toast("Menu prices saved. Your next answer and handshake will use them.")}}
function showCalendar(){openModal("SIMULATED CONNECTOR","Calendar signal",`<div class="limit-list"><div><strong>Client dinner with Acme</strong><br>Tonight · 19:00 · 4 attendees · Berlin Mitte</div><div>This is a demo calendar event. Confirming it adds business dinner context to the agent.</div></div><div class="modal-actions"><button id="useCalendar">Use this signal</button></div>`);$("#useCalendar").onclick=()=>{$("#occasion").value="Business dinner";$("#partySize").value=4;state.signals.set("Calendar","client dinner");renderSignals();closeModal();appendMessage("agent","I noticed a client dinner tonight. I’ll prioritize a business-appropriate choice.")}}
function showWeather(){openModal("SIMULATED CONNECTOR","Weather signal",`<div class="limit-list"><div><strong>Light rain around 19:00</strong><br>14°C · 80% chance of rain</div><div>The agent can turn this into an indoor-seating preference without sharing the full forecast.</div></div><div class="modal-actions"><button id="useWeather">Prefer indoor seating</button></div>`);$("#useWeather").onclick=()=>{state.signals.set("Weather","indoor preferred");renderSignals();closeModal();appendMessage("agent","Rain is likely, so I’ll keep indoor seating in the brief.")}}
function showCall(){openModal("FAKE CALL · NO LLM CREDIT USED","Fine Dining Agent is calling",`<div class="call-ui"><img src="./assets/mascot.png" alt=""><h3>What should I prioritize?</h3><p>This simulated call changes your live intent.</p><div class="call-options"><button data-call="quiet">Quiet room</button><button data-call="value">Lowest price</button></div></div>`);$$('[data-call]',modalBody).forEach(button=>button.onclick=()=>{if(button.dataset.call==="quiet"){state.signals.set("Call","quiet room priority");$("#occasion").value="Business dinner"}else{$("#budget").value=24;state.signals.set("Call","value priority")}renderSignals();closeModal();appendMessage("agent",button.dataset.call==="quiet"?"Understood—I’ll prioritize a quiet room.":"Understood—I’ll prioritize the strongest value under €24.")})}
async function useLocation(){if(!state.quota.location_available){toast("The one live location lookup has already been used.");return}if(!navigator.geolocation){toast("Location is not supported in this browser.");return}openModal("LIVE CONNECTOR","Finding restaurants nearby",`<div class="limit-list"><div>Waiting for browser location permission…</div><div>Your coordinates are used for this lookup and are not included in the retailer handshake.</div></div>`);navigator.geolocation.getCurrentPosition(async position=>{try{if(!state.token)await startSession();const data=await api("/demo/location",{token:state.token,latitude:position.coords.latitude,longitude:position.coords.longitude,accuracy:position.coords.accuracy});updateQuota(data.quota);const restaurants=data.restaurants||[];modalBody.innerHTML=restaurants.length?`<div class="restaurant-list">${restaurants.map((restaurant,index)=>`<article class="restaurant-item"><div><strong>${escapeHtml(restaurant.name||"Nearby restaurant")}</strong><span>${escapeHtml(restaurant.address||restaurant.cuisine||"")} · ${Math.round(restaurant.distance_m||0)}m</span></div><button data-restaurant="${index}">Use context</button></article>`).join("")}</div>`:`<div class="limit-list"><div>No restaurant results were available for this location. The preset restaurant remains active.</div></div>`;$$('[data-restaurant]',modalBody).forEach(button=>button.onclick=()=>{const item=restaurants[Number(button.dataset.restaurant)];state.signals.set("Location",item.name||"nearby restaurant");renderSignals();closeModal();appendMessage("agent",`I found ${item.name}. For this limited demo I’ll keep Maison Lumière’s preset menu, but use the nearby-location context.`)})}catch(error){modalBody.innerHTML=`<div class="limit-list"><div>${escapeHtml(error.message)}</div></div>`}},error=>{modalBody.innerHTML=`<div class="limit-list"><div>Location was not shared: ${escapeHtml(error.message)}</div></div>`},{enableHighAccuracy:false,timeout:12000,maximumAge:60000})}

async function runHandshake(){if(state.busy||!state.quota.remaining_handshakes)return;state.busy=true;const button=$("#connectAgents");button.disabled=true;button.textContent="Connecting…";try{await syncConfig();const data=await api("/demo/handshake",{token:state.token});updateQuota(data.quota);$("#handshakeEmpty").hidden=true;$("#eventStream").innerHTML="";$("#offerCard").hidden=true;for(const event of data.events){const item=document.createElement("li");item.innerHTML=`<small>${escapeHtml(event.speaker)} · ${escapeHtml(event.action)}</small><strong>${escapeHtml(event.message)}</strong>`;$("#eventStream").append(item);await wait(430)}const offer=data.offer;$("#offerTitle").textContent=offer.item.name;$("#offerDetails").textContent=`${offer.item.description} · ${offer.party_size} guests · ${offer.promotion}`;$("#listPrice").textContent=`€${offer.list_price.toFixed(2)}`;$("#offerPrice").textContent=`€${offer.offer_price.toFixed(2)}`;$("#budgetCheck").textContent=`Within €${offer.budget_per_person.toFixed(2)} budget`;$("#offerCard").hidden=false;$("#offerCard").focus()}catch(error){toast(error.message)}finally{state.busy=false;button.textContent="Connect agents →";button.disabled=!state.quota.remaining_handshakes}}
function price(value){const match=String(value).match(/[\d,.]+/);return match?Number(match[0].replace(",",".")):0}function wait(ms){return new Promise(resolve=>setTimeout(resolve,ms))}function escapeHtml(value){return String(value??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}

$("[data-start]").addEventListener("click",startSession);$("#showLimits").addEventListener("click",showLimits);$("#closeModal").addEventListener("click",closeModal);modal.addEventListener("click",event=>{if(event.target===modal)closeModal()});document.addEventListener("keydown",event=>{if(event.key==="Escape"&&!modal.hidden)closeModal()});
$$('[data-tool]').forEach(button=>button.addEventListener("click",()=>({menu:showMenu,location:useLocation,calendar:showCalendar,weather:showWeather,call:showCall}[button.dataset.tool]())));$$('[data-choice] button').forEach(button=>button.addEventListener("click",()=>button.classList.toggle("selected")));$$('.suggested-questions button').forEach(button=>button.addEventListener("click",()=>askAgent(button.textContent)));$("#chatForm").addEventListener("submit",event=>{event.preventDefault();const input=$("#chatInput");const text=input.value;input.value="";askAgent(text)});$("#connectAgents").addEventListener("click",runHandshake);$("#restartDemo").addEventListener("click",()=>location.reload());renderSignals();
